USE TTB_DB
---DROP TABLE TBL_USER
CREATE TABLE TBL_USER(USER_ID INT PRIMARY KEY,
USERNAME VARCHAR(50)NOT NULL,
PASSWORD VARCHAR(15) NOT NULL,
SECURITY_QUESTION VARCHAR(50) NOT NULL ,
SECURITY_ANSWER VARCHAR(50) NOT NULL,
FULL_NAME VARCHAR(50) NOT NULL,
DOB DATE NOT NULL,
MAIL_ID VARCHAR(100)NOT NULL,
GENDER VARCHAR(10)NOT NULL,
MOBILE_NO VARCHAR(10) NOT NULL,
DOOR_NO VARCHAR(20)NOT NULL,
STREET_NAME VARCHAR(40)NOT NULL,
CITY VARCHAR(30)NOT NULL,
STATE VARCHAR(40) NOT NULL,
PINCODE VARCHAR(10)NOT NULL,
CREATED_BY VARCHAR(20)NOT NULL,
CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
MODIFIED_BY VARCHAR(20)NOT NULL,
MODIFIED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
RECORDSTATUS BIT DEFAULT 1,
ROWGUID VARCHAR(MAX) DEFAULT NEWID());

SELECT * FROM TBL_USER;



----list of users----
CREATE PROCEDURE SP_USER_DETAILS
AS
BEGIN
SELECT * FROM TBL_USER;
END;
EXECUTE SP_USER_DETAILS;

		----------------------SELECT-----------
	CREATE PROCEDURE SP_SELECT_USER_DETAILS
		@USER_ID INT
		AS
		BEGIN
		SELECT * FROM TBL_USER WHERE USER_ID = @USER_ID 
		END;
EXECUTE SP_SELECT_USER_DETAILS
@USER_ID = 02


------insert tbl_user----------
---DROP PROCEDURE SP_INSERT_USER_DETAILS

CREATE PROCEDURE SP_INSERT_USER_DETAILS
@USER_ID INT,
@USERNAME VARCHAR(20),
@PASSWORD VARCHAR(20),
@SECURITY_QUESTION VARCHAR(20),
@SECURITY_ANSWER VARCHAR(20),
@FULL_NAME VARCHAR(20),
@DOB DATE,
@MAIL_ID VARCHAR(20),
@GENDER VARCHAR(20),
@MOBILE_NO VARCHAR(20),
@DOOR_NO VARCHAR(20),
@STREET_NAME VARCHAR(20),
@CITY VARCHAR(20),
@STATE VARCHAR(40),
@PINCODE VARCHAR(20),
@CREATED_BY VARCHAR(20),
@MODIFIED_BY VARCHAR(20)
AS
BEGIN
INSERT INTO TBL_USER (USER_ID,USERNAME,PASSWORD,
SECURITY_QUESTION,SECURITY_ANSWER,FULL_NAME,DOB,MAIL_ID,GENDER,MOBILE_NO,DOOR_NO,STREET_NAME,CITY,STATE,PINCODE,CREATED_BY,MODIFIED_BY) 
VALUES (
		    @USER_ID,
			@USERNAME ,
			@PASSWORD ,
			@SECURITY_QUESTION ,
			@SECURITY_ANSWER ,
			@FULL_NAME ,
			@DOB ,
			@MAIL_ID ,
			@GENDER ,
			@MOBILE_NO ,
			@DOOR_NO ,
			@STREET_NAME ,
			@CITY ,
			@STATE,
			@PINCODE ,
			@CREATED_BY ,
			@MODIFIED_BY )
END;
EXECUTE SP_INSERT_USER_DETAILS
            @USER_ID = 02,
			@USERNAME ='RAM',
			@PASSWORD ='RAM123',
			@SECURITY_QUESTION = 'nick name' ,
			@SECURITY_ANSWER ='ram2',
			@FULL_NAME ='RAMKRISH' ,
			@DOB = '2021/01/21' ,
			@MAIL_ID  = 'RAM@GMAIL.COM',
			@GENDER = 'MALE' ,
			@MOBILE_NO  = '9876512345',
			@DOOR_NO = 'A13',
			@STREET_NAME ='ABS ROOD' ,
			@CITY ='CHENNAI',
			@STATE ='TAMILNADU',
			@PINCODE = '678987',
			@CREATED_BY ='ram',
			@MODIFIED_BY ='ram'


------DELETE USER DETAILS------------------
CREATE PROCEDURE SP_DELETE_USER_DETAILS
@USER_ID INT
AS
BEGIN
DELETE FROM TBL_USER WHERE USER_ID= @USER_ID
END;
EXECUTE SP_DELETE_USER_DETAILS
@USER_ID =02

--------------------UPDATE USER DETAILS-------------------------------
---DROP PROCEDURE SP_UPDATE_USER_DETAILS

CREATE PROCEDURE SP_UPDATE_USER_DETAILS
(@USER_ID INT,
@USERNAME VARCHAR(20),
@PASSWORD VARCHAR(20),
@SECURITY_QUESTION VARCHAR(20),
@SECURITY_ANSWER VARCHAR(20),
@FULL_NAME VARCHAR(20),
@DOB DATE,
@MAIL_ID VARCHAR(20),
@GENDER VARCHAR(20),
@MOBILE_NO VARCHAR(20),
@DOOR_NO VARCHAR(20),
@STREET_NAME VARCHAR(20),
@CITY VARCHAR(20),
@STATE VARCHAR(40),
@PINCODE VARCHAR(20),
@MODIFIED_BY VARCHAR(20)
)
AS
BEGIN
UPDATE TBL_USER
SET     USERNAME = @USERNAME,
		PASSWORD = @PASSWORD,
		SECURITY_QUESTION = @SECURITY_QUESTION,
		SECURITY_ANSWER = @SECURITY_ANSWER ,
		FULL_NAME = @FULL_NAME,
		DOB = @DOB ,
		MAIL_ID = @MAIL_ID ,
		GENDER = @GENDER,
		MOBILE_NO = @MOBILE_NO,
		DOOR_NO = @DOOR_NO,
		STREET_NAME = @STREET_NAME,
		CITY = @CITY,
		STATE =@STATE,
		PINCODE = @PINCODE,
		MODIFIED_BY = @MODIFIED_BY
WHERE USER_ID = @USER_ID
END;

EXECUTE SP_UPDATE_USER_DETAILS
            @USER_ID = 02,
			@USERNAME ='RAM',
			@PASSWORD ='RAM123',
			@SECURITY_QUESTION = 'nick name' ,
			@SECURITY_ANSWER ='ram2',
			@FULL_NAME ='RAMKRISH KUMAR',
			@DOB = '2021/01/21',
			@MAIL_ID  = 'RAM@GMAIL.COM',
			@GENDER = 'MALE' ,
			@MOBILE_NO  = '9876512345',
			@DOOR_NO = 'A13',
			@STREET_NAME ='ABS ROOD' ,
			@CITY ='CHENNAI',
			@STATE ='KERALA',
			@PINCODE = '678987',
			@MODIFIED_BY ='ram'


------Master table---etl--
USE JUHI_DB

DROP TABLE TBL_TIME;

CREATE TABLE TBL_TIME(DATE_ID INT PRIMARY KEY,
ARRIVAL_DATE varchar(50)   ,
DEPARTURE_DATE varchar(50)  ,
CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'ADMIN',
CREATED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
MODIFIED_BY VARCHAR(50) NOT NULL DEFAULT 'ADMIN',
MODIFIED_DATE DATETIME NOT NULL DEFAULT GETDATE(),
RECORD_STATUS BIT DEFAULT 1,
ROWGUID VARCHAR(MAX) DEFAULT NEWID());


SELECT * FROM TBL_TIME;